# Generated by Django 4.0.3 on 2022-03-23 12:48

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rename_full_name_employee_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=30)),
                ('filial', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
            managers=[
                ('appeal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='shortnewsonmainpage',
            managers=[
                ('sh_news', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='shortnewsonmainpage',
            name='short_news_header',
            field=models.CharField(default='Заголовок', max_length=30),
        ),
        migrations.AlterField(
            model_name='shortnewsonmainpage',
            name='short_news_photo',
            field=models.ImageField(upload_to='images/news/'),
        ),
    ]
