# Generated by Django 4.0.2 on 2022-03-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_appeal_alter_shortnewsonmainpage_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_append',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
