# Generated by Django 4.0.2 on 2022-03-25 13:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_remove_document_date_append_document_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('doc_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('news_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
    ]
