# Generated by Django 4.0.2 on 2022-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_сhairman_chairman_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_title',
            field=models.CharField(default='название новости', max_length=255),
        ),
    ]
