# Generated by Django 4.0.2 on 2022-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_news_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(upload_to='images/page_news/'),
        ),
        migrations.AlterField(
            model_name='shortnewsonmainpage',
            name='short_news_photo',
            field=models.ImageField(upload_to='images/main_news/'),
        ),
    ]
