# Generated by Django 4.0.2 on 2022-03-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_news_news_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/page_news/')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_photo',
        ),
        migrations.AddField(
            model_name='news',
            name='news_photo',
            field=models.ManyToManyField(to='general.NewsPhoto'),
        ),
    ]
