# Generated by Django 4.0.2 on 2022-03-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_newsphoto_remove_news_news_photo_news_news_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_photo',
        ),
        migrations.AddField(
            model_name='news',
            name='news_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.newsphoto'),
            preserve_default=False,
        ),
    ]
