# Generated by Django 4.0.2 on 2022-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_remove_news_news_photo_news_news_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_photo',
        ),
        migrations.AddField(
            model_name='news',
            name='news_photo',
            field=models.ManyToManyField(to='general.NewsPhoto'),
        ),
    ]
