# Generated by Django 4.0.2 on 2022-03-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_remove_news_news_photo_news_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsphoto',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
